<?php

namespace Tests\Feature\Api;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class LoginApiTest extends TestCase
{
    /**
     * A basic feature test example.
     *
     * @return void
     */

    use RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        \Artisan::call('passport:install', ['-vvv' => true]);
    }

    public function test_a_user_can_login_with_email_and_password()
    {
        $this->withoutExceptionHandling();

        $user = \App\Models\User::factory()->create();

        $this->postJson(route('api.login'), [
            'email' => $user->email,
            'password' => 'password',
        ])->assertOk()
            ->assertJson([
                'success' => true,
                'message' => 'User login successfully.',
            ])
            ->assertJsonStructure([
                "success",
                "data" => [
                    "user" ,
                    "token",
                ],
                "message",
            ]);
    }

    public function test_if_user_email_is_not_available_then_it_return_error()
    {

        $this->post(route('api.login'), [
            'email' => 'k998@gg.com',
            'password' => '12345678'
        ])
            ->assertUnauthorized();
    }

}
